name: flutter_amazon_clone
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  badges: ^3.1.2
  carousel_slider: ^4.2.1
  cloudinary_public: ^0.23.1
  dotted_border: ^2.1.0
  file_picker: ^6.1.1
  fl_chart: ^0.64.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_rating_bar: ^4.0.1
  http: ^1.1.0
  intl: ^0.18.1
  pay: ^1.1.2
  provider: ^6.1.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/.env
    - assets/images/
    - assets/gpay.json
    - assets/applepay.json
